### ISSUE TITLE
Add the ability to see the changelog from within the app

### ISSUE THREAD

**Issue by amxmln** [elk-zone/elk#1024]
### Clear and concise description of the problem

There are plenty of new releases and I’m always curious to see what’s changed, but as far as I can tell the only way to do so is visit the "releases" page here on GitHub, which isn’t very discoverable.

### Suggested solution

I think it would be ideal if clicking the version number would open a modal containing the changelog, or at least the information for the current release.

### Alternative

Alternatively, clicking the version number could also open the releases page.

Or instead of showing the changelog via the version number, it could be shown in the "update available" notification? 🤔

**Comment by prohr** [comment]
Alternative 1 is probably as easy as a suitably-quoted:

undefined --> https://github.com/elk-zone/elk/releases

on or around here:

https://github.com/elk-zone/elk/blob/main/pages/settings/about/index.vue#L37

However, that seems **way** too geeky for an end-user feature.  Likewise, alternative 2 doesn't make sense, since this is a web service.  If you don't trust your provider to upgrade you to the latest + greatest, why are you using it?

If core devs mark this as WONTFIX, consider that a signal that they're aiming for mass usage.  ;-)

**Comment by amxmln** [comment]
Hm, I’m not sure I agree that this is too geeky. Most app stores offer a way to see what’s changed between releases and Elk themselves post links to the release notes on Mastodon for a new release. Regardless of that, however, I don’t see how this feature would negatively impact users who aren’t interested? :thinking: 

Here’s my use-case: I’m waiting for some features, like accent colour support for example, to be implemented. Right now, I have to either go check the settings every time a new release is dropped, or manually check out the releases page by searching for the repo and clicking into it to see if it was added. If I don’t do that, I have no way of knowing until I accidentally stumble over it.

**Comment by patak-dev** [comment]
Implemented in https://github.com/elk-zone/elk/commit/f78a7cd98d860218c38b84a3ef4f32baeb9f978b
