### ISSUE TITLE
Clickable links in image Alt

### ISSUE THREAD

**Issue by zeroby0** [elk-zone/elk#1267]
### Clear and concise description of the problem

The Alt seems like a nice place to put image sources. 

- If there's multiple images, there's no confusion which source belongs to which image because the link is in the image alt, not in the toot body
- The links don't take up limited toot characters

The only downside to having links in images I see is poorly written screen-readers that might read out the link letter-by-letter.

If the links in Alt can be identified and made clickable in Elk, that would be pretty neat.

### Suggested solution

In the Alt popup, search for URLs in the image alt and replace them with anchor tags for the links.

https://github.com/sindresorhus/get-urls can find links in strings.

### Alternative

Show a list of links in the description, below the description.

### Additional context

I've tried search+replace links with `<a href=''>link</a>` in image Alt, but it's inserted as-is as a string, instead of being parsed as HTML. 

Naively letting all text in Alt be parsed as HTML is dangerous so we would need a good way to insert anchor tags where the URLs are.

**Comment by ZMYaro** [comment]
> The Alt seems like a nice place to put image sources.
Alt text is absolutely not the place for that.  Alt text is only supposed to be an alternative text substitute for the image if the user is unable to see the image (due to the image failing to load, the user being visually impaired, the browser not showing the image, etc.).  It is _not_ supposed to be used as a caption or source link.

**Comment by zeroby0** [comment]
Okay then
