### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by nileshtrivedi** [elk-zone/elk#1406]
LaTeX is not rendered: https://elk.zone/mathstodon.xyz/@newb/109694427669924743

<img width="574" alt="image" src="https://user-images.githubusercontent.com/19304/214106492-160bd46f-d880-4b91-adb8-3ba82c2c3723.png">

See Mathstodon for comparison: https://mathstodon.xyz/@newb/109694427669924743

<img width="580" alt="image" src="https://user-images.githubusercontent.com/19304/214106538-82a27c10-4c54-4fe6-a2a3-e5c65b19bf31.png">

**Comment by Fastidious** [comment]
I believe Mathtodon modified code at their end to allow the rendering you see, and seek. I might be wrong, but I think what you ask might be beyond Elk’s scope. Again, I might be 100% wrong.

**Comment by ayoayco** [comment]
I believe we supported Markdown and Syntax highlighting because the audience of Elk leans heavily on the Tech/Programmers crowd. 

He had some discussions earlier about LaTex and the general feeling is that LaTeX is going to be way noisier than MarkDown when viewed from clients that do the support it.

**Comment by patak-dev** [comment]
Even if it isn't hard to implement, I think that LaTeX signal-to-noise ratio is very low as you said above. I think this is an example where it should be supported across the board or not supported at all. Or it may be supported in a fork for a community where everyone will use it.

**Comment by ayoayco** [comment]
Yeah agree, probably best if we leave this for forks to implement if they want.

Or another idea maybe in the future we can support easy plugin/extension for formatting if admins deploying elk want that.

**Comment by Jawvig** [comment]
Or maybe plugins that can be enabled on the client rather than at the server? As a reader of some mathstodon.xyz toots but resident of another server, I'd like to choose to read those toots with rendered maths.

Also, it seems to me that the argument that "LaTeX signal-to-noise ratio is low and therefore we shouldn't support rendering it" seems to presupposes that supporting the rendering would encourage the writing of it. If that's the thrust of the argument, and apologies if I've misunderstood or misrepresented it, then I'd offer two counterpoints:
1. Authoring of LaTeX is already happening, so the argument could be applied in reverse: Toots containing LaTeX currently have a low signal-to-noise ratio, and adding support for rendering LaTeX would increase the signal-to-noise ratio in those toots. 
2. I'd say it's unproven that Elk adding support for rending LaTeX would encourage its use in more toots. It might be that it doesn't cause any more use of LaTeX than is currently already happening, which feels more likely to me (gut feel).

At any rate, having an option to turn on LaTeX rendering on the client, where by default it's turned off, ought to alleviate any worry about Elk encouraging its further use.

**Comment by ayoayco** [comment]
We have an open Plugins System discussion on #33 

I think that’s also a good way to move forward for edge cases/features like LaTeX rendering. Please offer some ideas in that discussion 🙏
