### ISSUE TITLE
Cleanup URL from "birdsite" 

### ISSUE THREAD

**Issue by subcalc** [elk-zone/elk#1545]
The tracking should be removed from the URL. 
Otherwise Twitter will benefit from the extra traffic generated.
Twitter won't let you tweet mastodon links, so why should we toot Twitter?

Twitter API ToS ask explicitly to don't tamper with URL and display them as provided. That's why those aren't cleaned up on the bridge (bot) site.

https://imgur.com/a/LOa6U2e

**Comment by ayoayco** [comment]
This is objectively something Mastodon should do on their end. If the user wants to post a link with this format and Mastodon allows it, Elk, as a client application, should not tamper with it. It's a slippery slope if we start modifying what users post by checking for keywords.

**Comment by subcalc** [comment]
@ayoayco the tweet bridges are a bot. They have to retweet the complete URL according to the API ToS otherwise they will be banned. If not the client application the instance should have the option to strip the tracking, but it will mean extra calculations for the servers that are already busy with the influx of new users. It would be nice if the option is turned off by default

**Comment by ZMYaro** [comment]
Just clear one thing up, [UTM parameters](https://en.wikipedia.org/wiki/UTM_parameters) are not exclusively a Twitter thing.  I would be on board with an _option_ to strip known tracking parameters from links.  I generally try to push against overwhelming users with too many settings, but I think it is necessary in this case because we would be modifying the actual content of posts.

**Comment by tcely** [comment]
You might want to install https://fedilab.app/wiki/untrackme/ for this more general link clean up.

**Comment by antfu** [comment]
Consider as out-of-scope, as this is objective and already possible to solve with a browser extension.
