### ISSUE TITLE
Sending a PM

### ISSUE THREAD

**Issue by paranoidfactoid** [elk-zone/elk#1670]
If you try to send a PM, write text, and happen to touch outside the text window, you lose everything you wrote.

It's maddening.

**Comment by zaidhaan** [comment]
This looks to be due to the overwriting argument to `openPublishDialog()` being `true` here:
https://github.com/elk-zone/elk/blob/958f5967b9fbf67b4e8fb3e93215adab65429c28/composables/masto/statusDrafts.ts#L135-L140

Fixing this issue would be trivial (simply change it to `false`). But it looks like both usages of `openPublishDialog()` are true in that file, and I wonder if that's intentional.

This was introduced in 9fca8eee3073719a6c3870272bc812d4a8dab530, so I'd be curious to know @sxzz if it was intentional to overwrite the draft by default.

**Comment by patak-dev** [comment]
@zaidhaan I think this was a regression, that PR introduced a bigger change. Feel free to PR change these two to remove the third argument from these two 👍🏼

**Comment by zaidhaan** [comment]
Okay, thanks.
