### ISSUE TITLE
Video upload error

### ISSUE THREAD

**Issue by ackzell** [elk-zone/elk#1674]
I think #595 came back?

![image](https://user-images.githubusercontent.com/601266/217600463-719f2c9a-43da-4b47-99ab-f592fb890bec.png)

One difference is that there is a warning on `MastoClient` this time I think
```#create is deprecated. Use MastoClient.v2.media.create instead undefined```

![image](https://user-images.githubusercontent.com/601266/217600506-6c5cb5c8-0326-4283-bd16-cafbdf0d2d5c.png)

**Comment by sapphi-red** [comment]
I got the same error. Uploading 16.2MB mov file to m.webtoo.ls throws "413 Payload Too Large".
It would be nice if elk can show the reason of the error (file size is too large).

**Comment by userquin** [comment]
@sapphi-red the new version is async for large file uploads, masto will await for the status, since the file upload has failed we get the fetch error when masto checking for the status (the multipart form returns 202 instead 200):

https://docs.joinmastodon.org/methods/media/#202-accepted

I'm going to use the instance `configuration.media_attachments` to add custom filter for the dialog (`supported_mime_types`) and using `image_size_limit` and `video_size_limit` to prevent the upload (new entries in the json files)
