### ISSUE TITLE
Multiline code-block only rendering first line

### ISSUE THREAD

**Issue by Jofkos** [elk-zone/elk#1840]
A toot containing a multiline code-block is not rendered correctly.

What it looks like on the original mastodon instance:
![Screenshot 2023-03-02 at 09 15 04](https://user-images.githubusercontent.com/3756385/222370957-f3752290-3e4f-4666-adef-5780e21e75cf.png)

What it looks like in elk:
![Screenshot 2023-03-02 at 09 15 15](https://user-images.githubusercontent.com/3756385/222371058-a1a74a45-8872-4c5f-a713-b8526df63b38.png)

For reference: [the toot in question](https://social.treehouse.systems/@alyssa/109933427007257424).

**Comment by zaidhaan** [comment]
Hmm, interesting. Looking at canary...

Bug exists here: https://main.elk.zone/social.treehouse.systems/@alyssa/109933427007257424
Bug does not exist here: https://main.elk.zone/mastodon.social/@alyssa@treehouse.systems/109933428692502002

If you view the [first link in alpha](https://elk.zone/social.treehouse.systems/@alyssa/109933427007257424), it redirects to the second link.

**Comment by zaidhaan** [comment]
I think I've gotten to the root of the problem.

For context, content being fed is the following:
```
<p>i just typed</p><pre><code>$ gup<br>$ up<br>$ frb<br>$ pub<br>$ lab 21426 m<br></code></pre><p>now thinking i might have an absurd number of shell aliases</p>
```

Eventually, the `<pre>` node finds its way here:
https://github.com/elk-zone/elk/blob/f3ad179c69700c504505a9a0fb366dc6e0b05eaf/composables/content-render.ts#L105-L113

And as we can see, only the first child is consumed. When in this case, there's multiple text nodes within the `<code>` block due to the existence of the `<br>` tags.
