### ISSUE TITLE
Content warning bug

### ISSUE THREAD

**Issue by ayoayco** [elk-zone/elk#1846]
### Discussed in https://github.com/elk-zone/elk/discussions/1801

<div type='discussions-op-text'>

<sup>Originally posted by **sbug0** February 19, 2023</sup>
Scrolling through the time line I saw this.
It's a content warning post but Elk is not showing it as such.
The images show how Elk show the post compared to Mastodon web.

<img width="609" alt="Elk" src="https://user-images.githubusercontent.com/122732288/219947513-b980bfde-cbf6-4cdf-940c-bb30f1f02aab.png">
<img width="582" alt="Mastodon" src="https://user-images.githubusercontent.com/122732288/219947519-4d59827e-715f-486e-bd6c-2cd3e928b83b.png">
</div>

**Comment by zaidhaan** [comment]
That toot reports a `status.sensitive` of `false`, which I find odd because [according to the code](https://github.com/mastodon/mastodon/blob/af578e8ce0aabdbe9c0cd3d72d6fa2cc30b7fc66/app/services/post_status_service.rb#L65), you would expect that if some spoiler text is present that it would set sensitive to true? (unless I'm missing something obvious)

Anyway I quickly tried switching the logic around a bit and this seemed to fix this particular issue for me, which may or may not be useful to you.

<details>
<summary>
View diff
</summary>

```diff
diff --git a/components/status/StatusContent.vue b/components/status/StatusContent.vue
index b4dbb6d..10914c6 100644
--- a/components/status/StatusContent.vue
+++ b/components/status/StatusContent.vue
@@ -20,7 +20,7 @@ const isFiltered = $computed(() => status.account.id !== currentUser.value?.acco
 
 // check spoiler text or media attachment
 // needed to handle accounts that mark all their posts as sensitive
-const hasSensitiveSpoilerOrMedia = $computed(() => status.sensitive && (!!status.spoilerText || !!status.mediaAttachments.length))
+const hasSensitiveSpoilerOrMedia = $computed(() => !!status.spoilerText || (status.sensitive && !!status.mediaAttachments.length))
 </script>
 
 <template>
```
</details>


[At one point](https://github.com/mastodon/mastodon/commit/5bf500338478f819a65d25636a0af61a482972d3), they did mention they would allow for content with spoiler text to be marked as non-sensitive (don't know if this still applies but I guess that's what's happening here?), so maybe `status.sensitive` being `false` isn't so surprising here.

**Comment by ayoayco** [comment]
Yeah status.sensitive is a bit confusing at the moment. But I think it’s safe to just follow what the default mastodon web app is doing here.

**Comment by zaidhaan** [comment]
Sorry for the ping @ayoayco but are you working on this? I think from my message I made it look like I wanted to PR this but I just wanted to give some observations I'd made

**Comment by ayoayco** [comment]
@zaidhaan Ah no worries, I’m not working on this but leaving for others to pickup if someone wants. 😉 also we don’t assume someone is working on an issue unless its assigned, so all good!
