### ISSUE TITLE
Usability issue when displaying replies to posts

### ISSUE THREAD

**Issue by jimmccool** [elk-zone/elk#1849]
Just realised that my problem with the web client (overall it's great - such elegant design) is the lack of affordance when replies to posts are displayed. 

I _thought_ that only 3 replies were ever available because there were no visible hints or clues to tell me that other replies
![elk](https://user-images.githubusercontent.com/22393188/222850489-e2dce453-08d9-4fa8-80dd-32ea5dab48c8.png)
 would be displayed if I scrolled down. All I saw was white space.

I only discovered this functionality by accident. A classic usability issue. Such important functionality needs to be explicit, not hidden.

Easy to fix by providing some affordance - show your users what they can do.

**Comment by zaidhaan** [comment]
A good example of this would be [this post](https://elk.zone/mastodon.art/@Curator/109750189766288012). At the time of posting this, it appears that there are 19 replies, but only 3 are visible... until you scroll around [half-way past the last reply](https://user-images.githubusercontent.com/5954994/222977963-176cf27d-a04c-4328-9eb3-ef6ea12fc17e.png).

<details>
<summary>Aside: Twitter design for larger tweets</summary>

Twitter behavior seems to be to automatically load replies triggered by scrolling (in a fashion similar to elk but better since users don't need to scroll more than half way past the page for new replies to pop up), and then eventually you'd come across this: (source: scrolling down from [this tweet](https://twitter.com/gdb/status/1632100205620527104))
![image](https://user-images.githubusercontent.com/5954994/222978177-f3393f97-937b-4149-b6dd-62beb3ae6531.png)
Perhaps that's something to take into consideration when loading larger toots in elk? (i.e. dynamically show items upon scrolling, but if there's too many, just add a button to show more items)
</details>

Anyway, the source of this behavior would be the `page-mode` prop here (introduced in #1201):
https://github.com/elk-zone/elk/blob/b72809c0487fa8d27d135639778dd8c2e972d861/pages/%5B%5Bserver%5D%5D/%40%5Baccount%5D/%5Bstatus%5D.vue#L95-L101

Which, according to the [vue-virtual-scroller docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md#page-mode) _"expands the virtual-scroller and uses the page viewport to compute which items are visible"_. That does indeed seem like the desired behavior, but it appears that's not what's happening?

Not sure if this is a bug related to vue-virtual-scroller, or whether it's a configuration issue.

**Comment by zaidhaan** [comment]
Ah, I think I might have this figured out, they have a [buffer](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md#buffer) prop which _"extend[s] the viewport considered when determining the visible items. For example, if you set a buffer of 1000 pixels, the virtual-scroller will start rendering items that are 1000 pixels below the bottom of the scroller visible area, and will keep the items that are 1000 pixels above the top of the visible area."_

But this feels like a bit of a hack, since it's intended to be a buffer size for items to be rendered **below the bottom of the scroller visible area**, and in this case it appears (for whatever reason), the _scroller visible area_ is not properly understood by vue-virtual-scroller.

What I've observed is:
* buffer of 0: You can scroll pretty much to the last visible item
![image](https://user-images.githubusercontent.com/5954994/222983775-194b8a63-f439-4852-9c29-4b57537115e7.png)

* buffer of 490 (half of my clientHeight): You can scroll almost halfway to the last visible item
![image](https://user-images.githubusercontent.com/5954994/222983972-89202f71-fa03-4fe2-b639-ffd4d5aba551.png)

* buffer of 880 (100px below my clientHeight): Very little space left at the bottom before new items kick in 
![image](https://user-images.githubusercontent.com/5954994/222984095-d0ba835c-2f3d-4f60-908f-96c16d09eb16.png)

* buffer of 980 (my clientHeight): This is what felt most intuitive to me, no blank areas appeared that might have confused me into thinking I'd reached the end of the thread.

So I think I'll PR a fix that sets the buffer size to the clientHeight.
