### ISSUE TITLE
Option to use a star icon instead of a heart icon for favourites

### ISSUE THREAD

**Issue by katullo11** [elk-zone/elk#2058]
Give users the option to change the "heart" icon for favourites to a "star" icon to be more aligned with Mastodon's official design system.

Reference: https://elk.zone/mastodon.uno/@amministratore/110304288599350691

**Comment by shuuji3** [comment]
I like this idea since it's the same as Mastodon UI so it will help those who are familiar with Mastodon migrate without friction. Also, sometimes people like to use the star icon for favorites (for example, there was a popular feature to switch the heart icon with the star icon in [BetterTweetDeck](https://better.tw/)).

**Comment by AstroOrbis** [comment]
Just putting this here: The star icon makes more sense for those migrating from Mastodon, but the heart makes more sense for those migrating from Twitter
