### ISSUE TITLE
Consider flipping the order of the Edit UI

### ISSUE THREAD

**Issue by joelanman** [elk-zone/elk#2276]
Thanks for your work!

Just a suggestion - whenever I edit I instinctively try to edit the top box, which is actually showing the existing post, not the bottom box which is the Edit UI.

I think this makes sense as:

a) When you compose a new post, the UI is at the top
b) Newer posts in timelines appear at the top
c) Editing is your primary task here, not seeing the original post

But others may disagree!

**Comment by shuuji3** [comment]
I sometimes had a similar confusion between these areas. While flipping the order of posts can be a solution, in the current edit UI, for example when the post has several images, the edit area becomes large in height and users may not be able to see the original post if we move it to the bottom (but maybe we could still adjust the layout).

Another potential solution might be to adjust the style of the original post so that we can clearly distinguish two posts.

This is the Mastodon example:
<img width="342" alt="Screenshot 2023-07-28 at 19 41 37" src="https://github.com/elk-zone/elk/assets/1425259/2bfc3192-2956-42a2-8de5-d1c7af5017ea">

**Comment by joelanman** [comment]
I am wondering if you really need to see the original post at all?

**Comment by shuuji3** [comment]
Yeah, that may not be much important. Actually, I noticed that editing this GitHub comment doesn't show the original comment but doesn't feel issues so much. 🙂

**Comment by patak-dev** [comment]
I also find the current UI confusing, I imagine it was done by copying Mastodon. At least personally, I would be fine to try it removing the original

**Comment by shuuji3** [comment]
I just tried to make two PRs for comparison:
- #2283 for hiding the original post area
  - Deploy Preview: https://deploy-preview-2283--elk-zone.netlify.app/home
- #2284 for flipping two post areas (original proposal)
  - Deploy Preview: https://deploy-preview-2284--elk-zone.netlify.app/home

**Comment by patak-dev** [comment]
I like both of them to be honest. Let's try hiding for now and we see if we get some feedback from users.
