### ISSUE TITLE
Elk.zone seemingly not working on latest version of MS Edge

### ISSUE THREAD

**Issue by suflors** [elk-zone/elk#2966]
![image](https://github.com/user-attachments/assets/54d4b0d9-d076-4fb3-af54-a83350bf2ca0)
This is all I see when I open up elk.zone after updating. I am on Version 129.0.2792.52 (Official build) (64-bit) of MS Edge. I have tried clearing cache and cookies, restarting edge, et cetera, nothing works.

**Comment by shuuji3** [comment]
Hi, thanks for reporting. This issue is being tracked in #2935. Unfortunately, there seems something incompatible with Chromium v129-based browser and we couldn't find a root cause yet due to a lack of error messages.

The current workaround is to use the Beta version of the browser which uses Chromium v130 or a non-Chromium-based browser such as Firefox. Sorry for inconvenience.
