### ISSUE TITLE
feat: user lists

### ISSUE THREAD

**Issue by ayoayco** [elk-zone/elk#372]
Implement creating / showing lists on Elk.

The Mastodon web client has this feature:

![Screenshot 2022-12-08 at 9 56 59 AM](https://user-images.githubusercontent.com/4262489/206403174-58d02e30-e80b-45ee-9ac4-6734205f4c4d.png)

**Comment by maegul** [comment]
In line with @jmarkel 's [comment](https://github.com/elk-zone/elk/issues/372#issuecomment-1368246424), I too am interested!  I like what I've seen of elk a lot so far, but for me the lists is kind of a must have and I'll stay with the default webview for now entirely because of the lack of lists in elk .

Generally though, this feels like a nice opportunity to innovate on the filtering the fire-hose front on the client side, to whatever extent that's feasible so I'll be keeping an eye on elk for sure!

**Comment by ayoayco** [comment]
@maegul these are good ideas! We've had some discussions lately on "pinning" public timelines, I guess hashtags could be pinned too.

Are you able to [create separate issues](https://github.com/elk-zone/elk/issues/new/choose) so we keep the scope of this one to user lists?

**Comment by kerim** [comment]
I would like to replace "home" with a list of my choice, as well as have a couple of other pinned lists that I check regularly. I would also like to be able to add people to lists when I follow them.

**Comment by kissu** [comment]
Even Twitter has that one nowadays, more friendly than ever. 😄 
<img width="610" alt="CleanShot 2023-01-18 at 18 53 06@2x" src="https://user-images.githubusercontent.com/5133074/213257457-39422aa9-7f43-4e88-b517-48a7ee76f472.png">

**Comment by gerwitz** [comment]
+1 for @kerim's scenario. I follow promiscuously but then use a "regulars" list for my daily timeline browse.

**Comment by LauraLangdon** [comment]
It would be super helpful to be able to add a user to a list directly from that user’s profile!

**Comment by keelancook** [comment]
I'll chime in here as well. Love the look of Elk. Can't use it until lists are in place. They are 100% how I organize all of my followers. Mastodon is too noisy otherwise. 

My ideal use case would be an app that allows me to completely edit the timeline options on the side. Allow me to choose whether or not I show "home" or "bookmarks" or "favorites" and give me the option to replace these with my own lists, or followed hashtags. That would speed up my use of Mastodon tenfold. 

On mobile, as much as I hate to say it, Twitter's new implementation is ideal by having your lists at the top of the feed for easy selection. There is one exception. A number of Mastodon apps allow you to swipe left or right in the timeline to switch lists by gesture navigation. If an app had the looks of Elk and that kind of functionality for navigating lists, it would be my immediate choice.

Also, as cluttered as it can get, I do often like using the multi-column advanced interface that allows showing multiple lists as columns on a wide screen. 

And finally, the option to mute a user from the home timeline once they are in a list is part of the Fedilabs android app. It's brilliant. You can just choose to do so when you follow someone and add them to a list. 

You all are doing great work. Elk is beautiful.

**Comment by boehs** [comment]
![image](https://user-images.githubusercontent.com/51836263/214916136-ac219651-ce0c-43da-b9e0-0bd93caabab7.png)

I'm working on this!

**Comment by isocny** [comment]
Also important is making it easy to 1) add people to lists 2) see who is on a list 3) see what lists someone is on.

**Comment by ayoayco** [comment]
Thanks for picking this up @boehs! 🎉

Just see what you can do to move this forward. We want feature parity with Mastodon web app first, then we can add organize the very nice suggestions into separate issues.

**Comment by boehs** [comment]
> Also important is making it easy to 1) add people to lists 2) see who is on a list 3) see what lists someone is on.

Agreed. I plan to add support for all of that in due time. I personally like incremental merges, and the first pull request that adds basic viewing is now ready for review (I mentioned one core member, but I don't have a specific preference:))

> We want feature parity with Mastodon web app first, then we can maybe organize the very nice suggestions from comments here into separate issues.

All of that sounds good to me!

**Comment by afk-mario** [comment]
> Also important is making it easy to 1) add people to lists 2) see who is on a list 3) see what lists someone is on.

Maybe will help someone, I made a web app to manage the accounts you follow in lists

https://github.com/afk-mario/federike/

**Comment by boehs** [comment]
> > Also important is making it easy to 1) add people to lists 2) see who is on a list 3) see what lists someone is on.
> 
> Maybe will help someone, I made a web app to manage the accounts you follow in lists
> 
> [afk-mario/federike](https://github.com/afk-mario/federike/)

this is funky! we'll probably have these features by the end of tomorrow, but I absolutely love the design on this :)

**Comment by boehs** [comment]
Hi everyone, quick update. You *should* be able to:

- add users from lists
- view users in lists
- remove users from lists
- view lists

in practice, there is a bug that didn't appear during the PR that is seriously degrading that functionality. I'm looking into it, but likely won't have much time this week.

**Comment by ayoayco** [comment]
Thanks @boehs! I don’t know if this is tracked, but do you see on mobile there still no three dots now on a profile?

![953E7BB2-9755-42CB-A718-FF092250DBA5](https://user-images.githubusercontent.com/4262489/215504516-23ecc5cb-1b24-4e9a-811b-40b364a74990.jpeg)

**Comment by boehs** [comment]
> Thanks @boehs! I don’t know if this is tracked, but do you see on mobile there still no three dots now on a profile?
> 
> ![953E7BB2-9755-42CB-A718-FF092250DBA5](https://user-images.githubusercontent.com/4262489/215504516-23ecc5cb-1b24-4e9a-811b-40b364a74990.jpeg)

Oop, that's my fault.

**Comment by boehs** [comment]
Hi All, I am so excited to announce elk now supports lists with parity to mastodon. We will continue to work on enhancing lists even further, but will do so in separate issues. If all goes well, lists will be available on elk tomorrow, and for now you can test them on https://main.elk.zone

Special thanks for @userquin's help in making the last little bit really much better then what I was planning.

Consider backing elk on [open collective](https://opencollective.com/elk) or [github sponsors](https://github.com/elk-zone)

Much love, Evan ❤️

**Comment by beejunk** [comment]
Everything I hoped for and more, @boehs ! Thank you so much for your work, Elk will definitely be my client of choice now.

**Comment by kerim** [comment]
Fantastic. I've now switched to Elk as my main web client. I do hope to see the ability to pin individual lists at some point, but this is already great!

**Comment by ayoayco** [comment]
Hello, been a while :)

There’s now a Mastodon setting to have “hide these posts from home” which I think will address a few ideas/comments in this issue. 

![Image](https://github.com/user-attachments/assets/30639236-a85b-4c1d-85b5-8f0779f930eb)
