### ISSUE TITLE
Follow Requests in Notifications

### ISSUE THREAD

**Issue by vwchu** [elk-zone/elk#709]
I set up my Mastodon account to require follow requests. So, I can manually control who can follow me by approving follow requests. I also set up my notifications to include follow requests. However, they don't seem to display correctly within the Notifications page nor is there a Follow Requests page or a Follow Requests tab within the Notifications page.

**Comment by hendrikmitk** [comment]
I just stumbled across this issue myself and had some serious trouble figuring out what the actual problem is. It wasn't until I looked at the Notification view in the Mastodon default web GUI that I realized this is about follow requests.

Here is a screenshot here showing the broken display.

![Screen Shot 2023-01-19](https://user-images.githubusercontent.com/61987146/213507611-a5ae29c4-f2e6-407b-83df-d542311ec7d9.jpg){:width="50%" height="auto"}

**Comment by windhamdavid** [comment]
I also just came across this issue.

**Comment by stephen304** [comment]
Also noticed this, the way it is right now, it just looks like that person's profile card is in your notifications for no reason, and the only action you can take is following / unfollowing them, instead of being able to accept or reject the follow request

**Comment by SDK4rma** [comment]
Indeed, it seems a "follow requests" menu/tab is missing
